const frontendStudentEmails = [
  "nicholasosiokhale@gmail.com",
  "jesseadekoya229@gmail.com",
  "oma612631@gmail.com",
  "dvictory273@gmail.com",
  "marvellousgodsave0@gmail.com",
  "royalifidon@gmail.com",
  "afotanmary@gmail.com",
  "divineonyema61@gmail.com",
  "emmanueltufus6@gmail.com",
  "victoruche180@gmail.com",
  "gboteshoo@gmail.com",
  "oikosuccess502@gmail.com",
  "mhidemartins06@gmail.com",
  "thankgodowoicho9@gmail.com",
  "victorahiwe906@gmail.com",
  "akubodavid17@gmail.com",
  "chidebelukosi@gmail.com",
  "tzyung73@gmail.com",
  "ikebidofrank@gmail.com",
  "iyanuloluawshina@gmail.com",
  "fatiulahi280@gmail.com",
  "anoziengozi859@gmail.com",
  "onyekachiste@gmail.com",
  "emmasochima0501@gmail.com",
  "sokowonci474@gmail.com",
  "jimohtemi11@gmail.com",
  "kamsichukwu96@gmail.com",
];

const backendStudentEmails = [
  "abahvector@gmail.com",
  "adeleomotayo@gmail.com",
  "afolabirichard334@gmail.com",
  "brightimosemi@gmail.com",
  "chigoziemogbonnaya@gmail.com",
  "chikodiagubosim053@gmail.com",
  "chisomnwachukwu2001@gmail.com",
  "daveedsmall75@gmail.com",
  "emmyebube11@gmail.com",
  "jessicaehinmosan@gmail.com",
  "elijaofosu@gmail.com",
  "emmanueljohnson503@gmail.com",
  "chinonsoraphael56@gmail.com",
  "ikechukwuokonkwo365@gmail.com",
  "ichekanujoseph359@gmail.com",
  "naomiudoma04@gmail.com",
  "ndimeleugochi777@gmail.com",
  "luckyinfotech1992@gmail.com",
  "ohamaperez6ix@gmail.com",
  "okonkwouchennaemmanuel95@gmail.com",
  "oladipupohadi820@gmail.com",
  "oludent@gmail.com",
  "desmondonuoha01@gmail.com",
  "thedestinyonuoha@gmail.com",
  "thejenniferoriaku@gmail.com",
  "paulegbeme3@gmail.com",
  "everistuschidubem6@gmail.com",
  "mayorogbanna@gmail.com",
];

const productStudentEmails = [
  "gboladeoyedeji@gmail.com",
  "stephendoris40@gmail.com",
  "bertillachidera@gmail.com",
  "oduducourage77@gmail.com",
  "gabrieljones.official@gmail.com",
  "chisom993@gmail.com",
  "mercygenieveve950@gmail.com",
  "abdulrahmontoppy@gmail.com",
  "charlesiheanyi99@gmail.com",
  "atolagbeabisoye27@gmail.com",
  "iwuhmicheal@gmail.com",
  "olayemiogunti75@gmail.com",
  "lebanyapeace@gmail.com",
  "david.jremiah@gmail.com",
  "kinsightpro@gmail.com",
  "abiolaoyindamola276@gmail.com",
  "Chidinmanwanekezie5@gmail.com",
  "estheroriaku048@gmail.com",
  "adeojedereka@gmail.com",
  "anthonyonyemaechi212000@gmail.com",
  "bukolathomas28@gmail.com",
  "gbadeboesther66@gmail.com",
  "kingsleykenechukwu785@gmail.com",
];

export const studentRoster = [
  ...frontendStudentEmails.map((email) => ({ email, track: "frontend" })),
  ...backendStudentEmails.map((email) => ({ email, track: "backend" })),
  ...productStudentEmails.map((email) => ({ email, track: "product" })),
].map((student) => ({
  ...student,
  email: student.email.trim().toLowerCase(),
}));

export const rosterTrackCounts = {
  frontend: frontendStudentEmails.length,
  backend: backendStudentEmails.length,
  product: productStudentEmails.length,
};
